apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gceme
    env: canary
    role: frontend
  name: gceme-frontend-canary
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: gceme
      env: canary
      role: frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gceme
        env: canary
        role: frontend
      name: frontend
    spec:
      containers:
      - command:
        - sh
        - -c
        - app -frontend=true -backend-service=http://gceme-backend:8080 -port=80
        image: gcr.io/cloud-solutions-images/gceme:1.0.0
        imagePullPolicy: Always
        name: frontend
        ports:
        - containerPort: 80
          name: frontend
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
